#!/bin/bash
set -e

#source /unsonic/bin/activate

UNSONIC="unsonic -c /unsonic/etc/config.ini"
if [[ -z $MISHMASH_DBURL ]]; then
    echo "MISHMASH_DBURL environment variable required."
    exit 1
fi

if [[ ! -f /unsonic/var/music.db ]]; then
    pass=$(pwgen 12)

    $UNSONIC sync
       $UNSONIC password admin "$pass" \
    && echo 1>&2 "admin password set to: $pass"
fi
$UNSONIC serve

#exec /bin/bash
