"""Added bookmarks

Revision ID: 1a3712302478
Revises: 270412b38b53
Create Date: 2018-07-13 21:29:27.120027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3712302478'
down_revision = '270412b38b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('un_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'],
                            name=op.f('fk_un_bookmarks_track_id_tracks'),
                            ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['un_users.id'],
                            name=op.f('fk_un_bookmarks_user_id_un_users'),
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_un_bookmarks'))
    )
    op.create_index('bookmarks_user_index', 'un_bookmarks', ['user_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bookmarks_user_index', table_name='un_bookmarks')
    op.drop_table('un_bookmarks')
    # ### end Alembic commands ###
