"""Added shares

Revision ID: 270412b38b53
Revises: 7d7ec3901142
Create Date: 2018-04-24 18:09:11.996553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270412b38b53'
down_revision = '7d7ec3901142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('un_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=22), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_visited', sa.DateTime(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['un_users.id'],
                            name=op.f('fk_un_shares_user_id_un_users'),
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_un_shares'))
    )
    op.create_index('shares_user_index', 'un_shares', ['user_id'], unique=False)
    op.create_index('shares_uuid_index', 'un_shares', ['uuid'], unique=False)

    op.create_table('un_share_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=22), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'],
                            name=op.f('fk_un_share_entries_album_id_albums'),
                            ondelete='CASCADE'),
    sa.ForeignKeyConstraint(
        ['playlist_id'], ['un_playlists.id'],
        name=op.f('fk_un_share_entries_playlist_id_un_playlists'),
        ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_id'], ['un_shares.id'],
                            name=op.f('fk_un_share_entries_share_id_un_shares'),
                            ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'],
                            name=op.f('fk_un_share_entries_track_id_tracks'),
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_un_share_entries'))
    )
    op.create_index('share_entries_share_index', 'un_share_entries',
                    ['share_id'], unique=False)
    op.create_index('share_entries_uuid_index', 'un_share_entries',
                    ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('share_entries_share_index', table_name='un_share_entries')
    op.drop_table('un_share_entries')
    op.drop_index('shares_user_index', table_name='un_shares')
    op.drop_table('un_shares')
    # ### end Alembic commands ###
