"""Added internet radio

Revision ID: 33bb0c204f1e
Revises: 1a3712302478
Create Date: 2018-07-14 15:07:11.642143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bb0c204f1e'
down_revision = '1a3712302478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('un_iradios',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('stream_url', sa.String(), nullable=False),
                    sa.Column('homepage_url', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['un_users.id'],
                        name=op.f('fk_un_iradios_user_id_un_users'),
                        ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_un_iradios')))
    op.create_index('iradios_user_index', 'un_iradios', ['user_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('iradios_user_index', table_name='un_iradios')
    op.drop_table('un_iradios')
    # ### end Alembic commands ###
